# program used to view pdfs
$pdf_previewer = "zathura";

$clean_ext = "run.xml bbl nlo nls tdo";
# latex program used to compile
$pdflatex = 'xelatex --shell-escape %O %S';
# turn on production of pdf files (for xelatex)
$pdf_mode = 1;
# turn off the production of dvi and ps files (for xelatex)
$postscript_mode = $dvi_mode = 0;

# Custom dependency and function for nomencl package 
add_cus_dep( 'nlo', 'nls', 0, 'makenlo2nls' );
sub makenlo2nls {
  system( "makeindex -s nomencl.ist -o \"$_[0].nls\" \"$_[0].nlo\"" );
}
